#!/bin/sh
pj=$(basename $(pwd))
echo '#!/bin/sh' >>$pj.pakk
echo mkdir "$pj" >>$pj.pakk
echo cd "$pj" >>$pj.pakk
git ls-tree -r HEAD \
| sed -r 's/^100(...) [^ ]+ .{40}\t(.+)/\1 \2/' \
| while read mode file; do
	dir=`dirname $file`
	[ "$dir" != '.' ] && echo "[ ! -d \"$dir\" ] && mkdir -p \"$dir\"" >>$pj.pakk
	echo "cat <<\"PAKK\" >>$file" >>$pj.pakk
	cat $file >>$pj.pakk
	echo PAKK >>$pj.pakk
	echo "chmod $mode $file" >>$pj.pakk
done;
chmod +x $pj.pakk
